-- 1.DATABASE EXPLORATION
-->> Explore All Object in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-->> Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
----------------------------------------------------------------------
-- 2.DIMENSIONS EXPLORATION
-->> Explore All Countries our Customers come from.
SELECT DISTINCT country from gold.dim_customers 

-->> Explore All Categories "The Major Divisions"
SELECT DISTINCT category FROM gold.dim_products;
SELECT DISTINCT subcategory FROM gold.dim_products;
SELECT DISTINCT product_name FROM gold.dim_products;
----------------------------------------------------------------------
-- 3.DATE EXPLORATION
-->> Find the Date of the first and last order
SELECT
MIN(order_date) first_order_date,
MAX(order_date) last_order_date
FROM gold.fact_sales;

-->> How many years of sales are available
SELECT
DATEDIFF(YEAR, MIN(order_date),MAX(order_date)) order_range_years
FROM gold.fact_sales;

-->> How many months of sales are available
SELECT
DATEDIFF(MONTH, MIN(order_date),MAX(order_date)) order_range_years
FROM gold.fact_sales;

-->> Find the youngest and oldest customer
SELECT
MIN(birthdate) oldest_birthdate,
DATEDIFF(YEAR,MIN(birthdate),GETDATE()) oldest_age,
MAX(birthdate) youngest_birthdate,
DATEDIFF(YEAR,MAX(birthdate),GETDATE()) youngest_age
FROM gold.dim_customers;
------------------------------------------------------------------------------
-- 4.MEASURES EXPLORATION
-->> Find the total sales.
SELECT
SUM(sales_amount) total_sales
FROM gold.fact_sales

-->> Show how many items are sold
SELECT
SUM(quantity) total_quantity
FROM gold.fact_sales

-->> Find the average selling price
SELECT
AVG(price) avg_price
FROM gold.fact_sales

-->> Find the total number of orders
SELECT 
COUNT(*) total_orders
FROM gold.fact_sales 

-->> Find the total number of products
SELECT
COUNT(product_id) total_products
FROM gold.dim_products

-->> Find the total number of customers
SELECT
COUNT(customer_id) total_customers
FROM gold.dim_customers

-->> Genarate report that shows all key metrics of the business
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) measure_value FROM gold.fact_sales  
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) FROM gold.fact_sales  
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) FROM gold.fact_sales 
UNION ALL
SELECT 'Total Orders' AS measure_name, COUNT(*) FROM gold.fact_sales  
UNION ALL
SELECT 'Total Products' AS measure_name, COUNT(*) FROM gold.dim_products
UNION ALL
SELECT 'Total Nr.Customers' AS measure_name, COUNT(customer_key) FROM gold.dim_customers 
--------------------------------------------------------------------------------------------
-- 5.MAGNITUDE ANALYSIS
-->> Find total customers by countries
SELECT
country,
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-->> Find total customers by gender
SELECT 
gender,
COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-->> Find total products by category
SELECT 
category,
COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-->> What is the average costs in each category?
SELECT
category,
AVG(cost) avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-->> What is the total revenue generated for each category?
SELECT
P.category,
SUM(F.sales_amount) total_revenue
FROM gold.fact_sales F
LEFT JOIN gold.dim_products P
ON P.product_key = F.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-->> What is the total revenue generated by each customer?
SELECT
C.customer_key,
C.first_name +' '+ C.last_name customer_name,
SUM(F.sales_amount) total_revenue
FROM gold.fact_sales F
LEFT JOIN gold.dim_customers C
ON C.customer_key = F.customer_key
GROUP BY C.customer_key, C.first_name +' '+ C.last_name
ORDER BY total_revenue DESC

-->> What is the distribution of sold items across countries?
SELECT
C.country,
SUM(F.quantity) total_sold_items
FROM gold.fact_sales F
LEFT JOIN gold.dim_customers C
ON C.customer_key = F.customer_key
GROUP BY C.country
ORDER BY total_sold_items DESC
----------------------------------------------------------------
-- 6.RANKING ANALYSIS
--> Which 5 products generate the highest revenue?
SELECT TOP 5
P.product_name,
SUM(F.sales_amount) total_revenue
FROM gold.fact_sales F
LEFT JOIN gold.dim_products P
ON F.product_key = P.product_key
GROUP BY P.product_name
ORDER BY total_revenue DESC

-->> What are the 5 worst-performing products in terms of sales
SELECT TOP 5
P.product_name,
SUM(F.sales_amount) total_revenue
FROM gold.fact_sales F
LEFT JOIN gold.dim_products P
ON F.product_key = P.product_key
GROUP BY P.product_name
ORDER BY total_revenue 

-->> Rank Products Based on Total Sales Performance
SELECT 
P.product_name,
SUM(F.sales_amount) total_revenue,
ROW_NUMBER() OVER(ORDER BY SUM(F.sales_amount) DESC) rank_products
FROM gold.fact_sales F
LEFT JOIN gold.dim_products P
ON F.product_key = P.product_key
GROUP BY P.product_name

-->> Find the top 10 customers who have generated the highest revenue
SELECT
*
FROM(
	SELECT 
		C.customer_key,
		C.first_name+' '+C.last_name customer_name,
		SUM(F.sales_amount) total_revenue,
		ROW_NUMBER() OVER(ORDER BY SUM(F.sales_amount) DESC) rank_customers
	FROM gold.fact_sales F
	LEFT JOIN gold.dim_customers C
	ON F.customer_key = C.customer_key
	GROUP BY C.customer_key,
	C.first_name+' '+C.last_name
)T WHERE rank_customers <=10

-->> Find the customers with the fewest orders placed
SELECT 
C.customer_key,
C.first_name+' '+C.last_name customer_name,
COUNT(DISTINCT F.order_number) total_orders
FROM gold.fact_sales F
LEFT JOIN gold.dim_customers C
ON F.customer_key = C.customer_key
GROUP BY C.customer_key,
C.first_name+' '+C.last_name 
HAVING COUNT(DISTINCT F.order_number) = 1
ORDER BY COUNT(F.order_number)